include:
- fission.py
kind: ArchiveUploadSpec
name: fission-py-8JA9

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: onb-br-enum-state-fn-4e37d069-c8a2-4805-93be-49ede181b767
  namespace: default
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://fission-py-8JA9
  environment:
    name: onb-br-enum-state-env
    namespace: default
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2023-01-05T15:32:55Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: onb-br-enum-state-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      SpecializationTimeout: 120
    StrategyType: execution
  concurrency: 500
  environment:
    name: onb-br-enum-state-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: onb-br-enum-state-fn-4e37d069-c8a2-4805-93be-49ede181b767
      namespace: default
  requestsPerPod: 10000
  resources:
    requests:
      cpu: 128m
      memory: 128Mi
    limits:
      cpu: 256m
      memory: 256Mi
