apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: 71c3de6a-efd6-424a-805a-8114fe720139
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: fn-get-state
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /enum/state
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /enum/state
