include:
- ./func/*
kind: ArchiveUploadSpec
name: func-d5sT

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: fn-get-state-a6e26ef5-6462-438b-9c70-a25d5aa96212
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: env-get-state
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-d5sT
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-05-23T17:55:32Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: fn-get-state
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 1
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 80
    StrategyType: execution
  concurrency: 500
  environment:
    name: env-get-state
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.get_enums
    packageref:
      name: fn-get-state-a6e26ef5-6462-438b-9c70-a25d5aa96212
      namespace: default
  requestsPerPod: 1
  resources: {}
