apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: 2ec5163c-bcf9-429e-b119-13413de0bc07
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: fn-get-state
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /enum/state
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /enum/state
